import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, ArrowLeft, Sun, Menu, X, Search, BookOpen, Compass, Crown, Sparkles, ChevronDown, ExternalLink } from 'lucide-react';
import { people, events, sources, locations } from './lore';
import './archive.css';
const base = import.meta.env.BASE_URL;
const assets = import.meta.glob('../assets/*.webp', { eager: true, query: '?url', import: 'default' });
const scenery = { hero: 'silvermoon.webp', woods: 'chants-eternels.webp', well: 'puits-de-soleil.webp', court: 'cour-royale.webp' };
const href = route => `${base}${route.replace(/^\//, '')}`;
const getPath = () => {
  const prefix = base.replace(/\/$/, '');
  const pathname = location.pathname;
  const route = pathname === prefix ? '/' : pathname.startsWith(`${prefix}/`) ? pathname.slice(prefix.length) : pathname;
  try { return decodeURI(route).replace(/\/$/, '') || '/'; }
  catch { return '/introuvable'; }
};
const nav = [['Dynastie', '/monarchie'], ['Chronologie', '/histoire'], ['Explorer', '/decouvrir'], ['Les sources', '/sources']];
function Link({ to, children, ...props }) { return <a href={href(to)} {...props}>{children}</a>; }
function Picture({ name, alt, className = '', eager = false }) { return <img className={className} src={assets[`../assets/${name}`]} alt={alt} loading={eager ? 'eager' : 'lazy'} decoding="async" />; }
function SourceLinks({ ids }) { return <div className="source-links"><BookOpen size={14}/><span>Sources</span>{ids.map(id => <a key={id} href={sources[id].url} target="_blank" rel="noreferrer">{sources[id].label}<ExternalLink size={11}/></a>)}</div>; }
function Eyebrow({ children }) { return <p className="kicker"><span/>{children}</p>; }
function SectionTitle({ eyebrow, title, children }) { return <div className="section-title"><div><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2></div>{children}</div>; }
export default function App() {
 const [path,setPath]=useState(getPath), [menu,setMenu]=useState(false), [query,setQuery]=useState(''), [searchOpen,setSearchOpen]=useState(false);
 const searchRef=useRef(null), searchButton=useRef(null);
 useEffect(()=>{const pop=()=>setPath(getPath());window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[]);
 useEffect(()=>{setMenu(false);setSearchOpen(false);document.title=`${path==='/'?'La mémoire du soleil':people.find(p=>path.endsWith(p.id))?.name||({'/monarchie':'La dynastie','/histoire':'Chronologie','/decouvrir':'Atlas de Quel’Thalas','/sources':'Sources et méthode','/culture':'Reliques et héritage'}[path]||'Archives')} | Sunstrider`;},[path]);
 useEffect(()=>{if(searchOpen)searchRef.current?.focus();},[searchOpen]);
 useEffect(()=>{const escape=e=>{if(e.key==='Escape'){setMenu(false);setSearchOpen(false);searchButton.current?.focus();}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[]);
 function navigate(e){const a=e.target.closest('a');if(!a||e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||a.target||a.hasAttribute('download'))return;const url=new URL(a.href);if(url.origin!==location.origin||!url.pathname.startsWith(base)||url.hash)return;e.preventDefault();history.pushState({},'',url.pathname);setPath(getPath());window.scrollTo({top:0,behavior:'instant'});document.getElementById('content')?.focus({preventScroll:true});}
 const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const matches=[...people.map(p=>({label:`${p.name} Sunstrider`,detail:p.title,to:`/personnages/${p.id}`})),...events.map(e=>({label:e.title,detail:e.era,to:`/histoire/${e.id}`})),...locations.map(l=>({label:l.name,detail:l.type,to:`/decouvrir/${l.id}`}))].filter(p=>normalize(`${p.label} ${p.detail}`).includes(normalize(query)));
 return <div className="archive" onClick={navigate}><a className="skip-link" href="#content">Aller au contenu</a>
 <header className="site-header"><Link to="/" className="brand" aria-label="Sunstrider, accueil"><Sun className="brand-mark" strokeWidth={1}/><span>SUNSTRIDER<small>LES ARCHIVES DE QUEL’THALAS</small></span></Link><nav aria-label="Navigation principale" className={menu?'open':''} id="main-nav">{nav.map(([label,to])=><Link key={to} to={to} aria-current={path.startsWith(to)?'page':undefined}>{label}</Link>)}</nav><div className="header-tools"><button ref={searchButton} aria-label="Rechercher dans les archives" aria-expanded={searchOpen} aria-controls="archive-search" onClick={()=>setSearchOpen(!searchOpen)}><Search size={19}/></button><Link to="/culture" className="header-cta">L’héritage <ArrowUpRight size={15}/></Link><button className="menu-toggle" aria-label={menu?'Fermer le menu':'Ouvrir le menu'} aria-expanded={menu} aria-controls="main-nav" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 {searchOpen&&<section className="search-panel" id="archive-search" aria-label="Recherche"><label htmlFor="archive-query">Que cherchez-vous dans les archives ?</label><div className="search-field"><Search size={20}/><input ref={searchRef} id="archive-query" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Un personnage, un événement, un lieu…"/><button aria-label="Fermer la recherche" onClick={()=>{setSearchOpen(false);searchButton.current?.focus();}}><X/></button></div><p aria-live="polite">{matches.length} résultat{matches.length!==1?'s':''}</p><div className="search-results">{matches.map(m=><Link key={m.to} to={m.to} onClick={()=>setSearchOpen(false)}><span>{m.label}<small>{m.detail}</small></span><ArrowUpRight size={17}/></Link>)}{!matches.length&&<p>Aucune archive ne correspond à cette recherche.</p>}</div></section>}
 <main id="content" tabIndex={-1}><RouteContent path={path}/></main>
 <footer><div className="footer-top"><Link to="/" className="brand"><Sun strokeWidth={1}/><span>SUNSTRIDER<small>LA MÉMOIRE DU SOLEIL</small></span></Link><p>Un royaume se transmet.<br/>Son histoire se raconte.</p><div><Link to="/sources">Sources & méthode</Link><Link to="/visite">Le salon RP</Link><a href="#content">Retour en haut ↑</a></div></div><div className="footer-bottom"><span>Projet de fans indépendant · Univers Warcraft © Blizzard Entertainment</span><span>Illustrations générées par IA · Interprétations artistiques</span></div></footer></div>;
}
function RouteContent({ path }) {
  const [section, slug, ...extra] = path.split('/').filter(Boolean);
  if (extra.length) return <NotFound/>;
  if (!section) return <Home/>;
  if (section === 'personnages') return <Biography id={slug}/>;
  if (section === 'histoire') return !slug || events.some(event => event.id === slug)
    ? <History initial={slug} key={path}/> : <NotFound/>;
  if (section === 'decouvrir' || section === 'lieux') return !slug || locations.some(place => place.id === slug)
    ? <Atlas initial={slug} key={path}/> : <NotFound/>;
  if (section === 'monarchie' && !slug) return <Dynasty/>;
  if (section === 'sources' && !slug) return <Sources/>;
  if (section === 'culture' && !slug) return <Heritage/>;
  // Preserve the old roleplay entry points, with explicit non-canonical labeling.
  if (['visite', 'actualites', 'contacts'].includes(section)) return <Roleplay/>;
  return <NotFound/>;
}
function Home(){return <>
 <section className="hero"><Picture name="silvermoon.webp" alt="Interprétation artistique de Lune-d’Argent, tours d’ivoire et bannières cramoisies" eager/><div className="hero-shade"/><div className="embers" aria-hidden="true"><i/><i/><i/><i/><i/></div><div className="hero-content"><Eyebrow>UNE DYNASTIE. UN ROYAUME. UN HÉRITAGE.</Eyebrow><h1>Le soleil se couche.<br/><em>La légende demeure.</em></h1><p>De l’exil de Dath’Remar à la chute de Kael’thas,<br className="desktop-break"/> entrez dans la mémoire de la maison Sunstrider.</p><div className="hero-actions"><Link className="button gold-button" to="/monarchie">Explorer la dynastie <ArrowUpRight size={18}/></Link><Link className="text-button" to="/histoire"><span className="circle-icon"><BookOpen size={16}/></span> Parcourir son histoire</Link></div></div><div className="hero-bottom"><span>QUEL’THALAS <span className="gold-dot">◆</span> ROYAUMES DE L’EST</span><a href="#dynasty-preview">DÉCOUVRIR <ChevronDown size={15}/></a><span>ILLUSTRATION · VISION D’ARTISTE</span></div></section>
 <div className="archive-ribbon"><span><Sun size={17}/> L’héritage des Haut-Soleil</span><p>Des origines à la fin de la lignée régnante</p><Link to="/sources">Une histoire sourcée <ArrowUpRight size={14}/></Link></div>
 <section className="section-wrap" id="dynasty-preview"><SectionTitle eyebrow="01 — LA MAISON SUNSTRIDER" title={<>Trois destins.<br/><em>Une mémoire.</em></>}><p>Un fondateur, un roi, un prince.<br/>Découvrez les figures qui ont façonné<br/>le destin de Quel’Thalas.</p></SectionTitle><Portraits/><div className="section-end"><span>Sunstrider · Haut-Soleil en français</span><Link to="/monarchie">Découvrir la succession <ArrowRight size={17}/></Link></div></section>
 <section className="history-preview section-wrap"><div><Eyebrow>02 — LE FIL DE L’HISTOIRE</Eyebrow><h2>De la splendeur<br/><em>aux cendres.</em></h2><p>Chaque époque laisse une empreinte.<br/>Suivez les événements qui ont changé le royaume.</p><Link to="/histoire" className="button outline-button">Ouvrir la chronologie <ArrowUpRight size={17}/></Link></div><div className="mini-timeline">{[events[1],events[3],events[6]].map((e,i)=><Link key={e.id} to={`/histoire/${e.id}`}><span className="timeline-index">0{i+1}</span><div><small>{e.era}</small><h3>{e.title}</h3></div><ArrowUpRight size={20}/></Link>)}</div></section>
 <section className="atlas-preview"><Picture name="chants-eternels.webp" alt="Vision artistique des bois dorés de Quel’Thalas"/><div className="atlas-preview-shade"/><div className="section-wrap"><Eyebrow>03 — LES TERRES DU SOLEIL</Eyebrow><h2>Au-delà<br/><em>de la couronne.</em></h2><p>Les bois, la capitale, le sanctuaire.<br/>L’histoire s’écrit aussi dans les lieux.</p><Link to="/decouvrir" className="button gold-button">Explorer Quel’Thalas <Compass size={17}/></Link></div></section>
 <section className="heritage-preview section-wrap"><div className="ornament" aria-hidden="true"><Sun strokeWidth={.6}/></div><div><Eyebrow>LA MÉMOIRE VIVANTE</Eyebrow><h2>Ce qu’il reste<br/><em>quand les rois tombent.</em></h2><p>Une lame, un Puits, un nom. Découvrez l’héritage des Sunstrider et la régence qui succède à leur dynastie.</p><Link to="/culture" className="text-link">Explorer l’héritage <ArrowRight size={17}/></Link></div></section></>;}
function Portraits(){return <div className="portrait-grid">{people.map((p,i)=><Link to={`/personnages/${p.id}`} className="portrait-card" key={p.id}><Picture name={p.image} alt={`Portrait interprété de ${p.name} Sunstrider`}/><span className="portrait-number">0{i+1} / SUNSTRIDER</span><div className="portrait-copy"><small>{p.title}</small><h3>{p.name}</h3><p>{p.quote}</p><span className="portrait-arrow"><ArrowUpRight size={21}/></span></div></Link>)}</div>;}
function PageIntro({label,title,text}){return <div className="page-intro section-wrap"><Link className="back-link" to="/">Accueil <span>/</span> Archives</Link><Eyebrow>{label}</Eyebrow><h1>{title}</h1><p>{text}</p></div>;}
function Dynasty(){const [selected,setSelected]=useState('dathremar');const person=people.find(p=>p.id===selected);return <><PageIntro label="LA MAISON SUNSTRIDER" title={<>L’éclat d’une dynastie.<br/><em>Les traces de sa chute.</em></>} text="La maison royale historique de Quel’Thalas. Une succession qui comporte aussi des noms que les sources ne nous ont pas transmis."/><section className="section-wrap no-top"><Portraits/></section><section className="section-wrap lineage-section"><SectionTitle eyebrow="LA SUCCESSION" title="Le fil de la couronne."/><p className="muted">Sélectionnez une figure. Les traits indiquent l’ordre de succession.</p><div className="lineage">{[['dathremar','Dath’Remar'],['unknown','Deux souverains'],['anasterian','Anasterian'],['kaelthas','Kael’thas']].map(([id,name])=>id==='unknown'?<div className="unknown-node" key={id}><span>◇</span><strong>{name}</strong><small>Noms non documentés</small></div>:<button key={id} aria-pressed={selected===id} onClick={()=>setSelected(id)}><Crown size={22}/><strong>{name}</strong><small>{people.find(p=>p.id===id).title}</small></button>)}</div><div className="lineage-detail" aria-live="polite"><div><Eyebrow>{person.title}</Eyebrow><h3>{person.name} Sunstrider</h3><p>{person.summary}</p></div><Link className="button outline-button" to={`/personnages/${person.id}`}>Lire la biographie <ArrowUpRight size={17}/></Link></div><SourceLinks ids={['dynasty']}/><div className="editorial-grid"><article><Eyebrow>PARENTÉ</Eyebrow><h3>Une branche éloignée</h3><p>Lyandra Sunstrider est une parente éloignée d’Anasterian, sans droit au trône. Son existence ne constitue pas une continuation de la lignée régnante.</p></article><article><Eyebrow>APRÈS KAEL’THAS</Eyebrow><h3>La régence demeure</h3><p>Lor’themar Theron conserve le titre de seigneur régent. Il ne devient pas un roi Sunstrider.</p><SourceLinks ids={['regent']}/></article></div></section></>;}
function Biography({id}){const p=people.find(p=>p.id===id);if(!p)return <NotFound/>;return <><section className="biography section-wrap"><div className="bio-image"><Picture name={p.image} alt={`Interprétation artistique de ${p.name}`} eager/><small>Portrait généré par IA · interprétation artistique</small></div><div><Link className="back-link" to="/monarchie"><ArrowLeft size={14}/> La dynastie</Link><Eyebrow>{p.title}</Eyebrow><h1>{p.name}<br/><em>Sunstrider</em></h1><p className="bio-era">{p.era}</p>{p.paragraphs.map(t=><p key={t}>{t}</p>)}<dl>{p.facts.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><SourceLinks ids={p.refs}/>{p.id==='kaelthas'&&<details className="spoiler"><summary>Épilogue · Shadowlands (spoilers)</summary><p>L’âme de Kael’thas se retrouve à Revendreth pour répondre de ses actes. Cet épilogue ne rétablit pas la dynastie sur Azeroth.</p><SourceLinks ids={['shadowlands']}/></details>}</div></section><section className="section-wrap related"><SectionTitle eyebrow="CHAPITRES ASSOCIÉS" title="Dans le fil de l’histoire."/>{events.filter(e=>e.person===id).map(e=><Link className="related-row" key={e.id} to={`/histoire/${e.id}`}><span>{e.era}</span><h3>{e.title}</h3><ArrowUpRight/></Link>)}</section></>;}
function History({initial}){const [active,setActive]=useState(Math.max(0,events.findIndex(e=>e.id===initial)));const e=events[active];return <><PageIntro label="LA CHRONOLOGIE" title={<>D’un exil naît<br/><em>une légende.</em></>} text="Huit repères pour parcourir l’histoire. Les périodes sont privilégiées aux dates lorsque leur précision n’est pas établie ici."/><section className="section-wrap no-top"><div className="timeline-layout"><div className="event-list" aria-label="Choisir un événement">{events.map((entry,i)=><button key={entry.id} onClick={()=>setActive(i)} aria-pressed={i===active}><span>{String(i+1).padStart(2,'0')}</span><div><small>{entry.era}</small><strong>{entry.title}</strong></div>{i===active&&<ArrowRight size={17}/>}</button>)}</div><article className="event-detail" aria-live="polite" key={e.id}><Picture name={scenery[e.image]} alt="Illustration d’ambiance du royaume"/><div><Eyebrow>{e.era}</Eyebrow><h2>{e.title}</h2><p>{e.text}</p>{e.person&&<Link className="text-link" to={`/personnages/${e.person}`}>Rencontrer {people.find(p=>p.id===e.person).name} <ArrowUpRight size={16}/></Link>}<SourceLinks ids={e.refs}/><div className="event-controls"><button disabled={active===0} onClick={()=>setActive(active-1)}><ArrowLeft size={17}/> Précédent</button><span>{active+1} / {events.length}</span><button disabled={active===events.length-1} onClick={()=>setActive(active+1)}>Suivant <ArrowRight size={17}/></button></div></div></article></div></section></>;}
function Atlas({initial}){const [active,setActive]=useState(locations.find(l=>l.id===initial)||locations[0]);return <><PageIntro label="L’ATLAS DU ROYAUME" title={<>Les terres<br/><em>du soleil éternel.</em></>} text="Quatre lieux pour comprendre l’héritage Sunstrider. Sélectionnez un repère pour découvrir son histoire."/><section className="section-wrap no-top"><div className="atlas-layout"><div><div className="map" aria-label="Carte schématique interactive de Quel’Thalas"><div className="map-land"/><span className="map-sea">LA GRANDE MER</span><span className="map-region">QUEL’THALAS</span><span className="map-compass">N<br/>✧</span>{locations.map(l=><button key={l.id} style={{left:`${l.x}%`,top:`${l.y}%`}} aria-pressed={active.id===l.id} onClick={()=>setActive(l)}><span className="map-pin"/><strong>{l.name}</strong></button>)}</div><p className="map-note">Carte schématique · positions indicatives · ne convient pas à la navigation en jeu.</p></div><article className="location-detail" aria-live="polite"><Picture name={scenery[active.image]} alt={`Évocation artistique : ${active.name}`}/><div><Eyebrow>{active.type}</Eyebrow><h2>{active.name}</h2><p>{active.text}</p><SourceLinks ids={active.refs}/></div></article></div><div className="era-note"><Sparkles size={22}/><div><h3>Un royaume qui évolue</h3><p>Les archives couvrent l’histoire de la dynastie. Pour les événements de Midnight, consultez la présentation officielle, qui contient des spoilers.</p><a href={sources.midnight.url} target="_blank" rel="noreferrer">Découvrir Midnight chez Blizzard <ArrowUpRight size={15}/></a></div></div></section></>;}
function Heritage(){const cards=[['LA LAME DYNASTIQUE','Felo’melorn','La lame est associée à Dath’Remar, Anasterian et Kael’thas. Elle relie trois destins au sein d’une même mémoire familiale.',['dynasty']],['LE CŒUR DU ROYAUME','Le Puits de soleil','Fondation, corruption, destruction puis restauration : ses transformations accompagnent les ruptures de l’histoire des elfes.',['well','restored']],['LE POUVOIR APRÈS LES ROIS','La régence','Le titre de Lor’themar exprime une continuité politique après la disparition de la dynastie régnante. Il ne fait pas de lui un membre de la maison Sunstrider.',['regent']],['LES LIMITES DU SAVOIR','Les silences des archives','Les deux souverains non nommés restent anonymes. Aucun nom, mariage ou descendant n’est ajouté pour combler les lacunes des sources.',['dynasty']]];return <><PageIntro label="RELIQUES & HÉRITAGE" title={<>La couronne tombe.<br/><em>La mémoire reste.</em></>} text="Objets, lieux et institutions prolongent l’histoire de la maison Sunstrider."/><section className="section-wrap no-top"><div className="editorial-grid heritage-cards">{cards.map(([label,title,text,refs])=><article key={title}><Sun/><Eyebrow>{label}</Eyebrow><h2>{title}</h2><p>{text}</p><SourceLinks ids={refs}/></article>)}</div></section></>;}
function Sources(){return <><PageIntro label="SOURCES & MÉTHODE" title={<>La légende mérite<br/><em>de la précision.</em></>} text="Une sélection documentée, pas une encyclopédie exhaustive. Chaque dossier renvoie aux références qui étayent son contenu."/><section className="section-wrap no-top"><div className="era-note"><BookOpen/><div><h3>Lire ces archives</h3><p>Le récit principal va des origines à The Burning Crusade. Shadowlands est traité dans un épilogue replié. Midnight est proposé comme prolongement externe. Les synthèses communautaires sont distinguées des publications officielles ; leurs références permettent de remonter aux jeux et aux ouvrages.</p><p>Les illustrations sont des créations générées par IA, pas des documents officiels ni des preuves du lore. Le salon RP est une création originale séparée.</p></div></div><div className="source-catalog">{Object.entries(sources).map(([id,s])=><a key={id} href={s.url} target="_blank" rel="noreferrer"><div><small>{s.publisher}</small><h3>{s.label}</h3></div><ArrowUpRight/></a>)}</div><p className="muted">Sélection vérifiée le 7 octobre 2026. Les sources peuvent évoluer. Les informations non établies ne sont pas complétées par invention.</p></section></>;}
function Roleplay(){const [type,setType]=useState('Voyageur');return <><PageIntro label="CRÉATION ORIGINALE · NON CANONIQUE" title={<>Le salon<br/><em>des voyageurs.</em></>} text="Un espace d’imagination inspiré de Quel’Thalas. Les propositions ci-dessous sont des créations RP, sans valeur de lore officiel."/><section className="section-wrap no-top"><div className="rp-panel"><Eyebrow>VOTRE ESCALE IMAGINAIRE</Eyebrow><h2>Quel rôle jouerez-vous ?</h2><div className="rp-options">{['Voyageur','Archiviste','Diplomate'].map(t=><button aria-pressed={t===type} key={t} onClick={()=>setType(t)}>{t}</button>)}</div><p aria-live="polite">{{Voyageur:'Imaginez une arrivée au crépuscule, un carnet de voyage et les reflets des tours sur vos pas.',Archiviste:'Votre personnage cherche un fragment de chronique. À vous d’inventer sa mission en distinguant vos ajouts des faits documentés.',Diplomate:'Imaginez une audience et les tensions d’une délégation. Ses règles et ses protagonistes relèvent de votre récit.'}[type]}</p><Link to="/sources" className="text-link">Retrouver les repères canoniques <ArrowRight size={16}/></Link></div></section></>;}
function NotFound(){return <><PageIntro label="ARCHIVE INTROUVABLE · 404" title="Ce chapitre manque aux archives." text="Le lien ne correspond à aucun dossier de cette collection."/><div className="section-wrap no-top"><Link className="button gold-button" to="/">Revenir à l’accueil <ArrowRight size={17}/></Link></div></>;}
