export const sources = {
  dynasty: { label: 'Maison Sunstrider', publisher: 'Warcraft Wiki · synthèse et références', url: 'https://warcraft.wiki.gg/wiki/House_of_Sunstrider' },
  founder: { label: 'Dath’Remar Sunstrider', publisher: 'Warcraft Wiki · biographie', url: 'https://warcraft.wiki.gg/wiki/Dath%27Remar_Sunstrider' },
  king: { label: 'Anasterian Sunstrider', publisher: 'Warcraft Wiki · biographie', url: 'https://warcraft.wiki.gg/wiki/Anasterian_Sunstrider' },
  prince: { label: 'Lumière sur Kael’thas', publisher: 'Blizzard · rétrospective du personnage', url: 'https://news.blizzard.com/fr-fr/article/19005493/lumiere-sur-kaelthas' },
  exile: { label: 'The Burning Crusade : résumé des épisodes précédents', publisher: 'Blizzard · histoire', url: 'https://worldofwarcraft.blizzard.com/fr-fr/news/23679744/burning-crusade-classic-the-story-so-far' },
  well: { label: 'Du Puits de soleil à Midnight', publisher: 'Blizzard · rétrospective', url: 'https://worldofwarcraft.blizzard.com/fr-fr/news/24264003/explore-as-terras-lendas-e-o-legado-de-the-burning-crusade-a-midnight' },
  restored: { label: 'Épilogue du plateau du Puits de soleil', publisher: 'Warcraft Wiki · dialogues du jeu', url: 'https://warcraft.wiki.gg/wiki/Sunwell_Plateau_epilogue' },
  regent: { label: 'À l’ombre du soleil', publisher: 'Blizzard · nouvelle de Sarah Pine', url: 'https://media.blizzard.com/wow/lore/pdfdownload/leader-story/lorthemar-theron/lorthemar-theron-frFR.pdf' },
  shadowlands: { label: 'L’avenir de World of Warcraft', publisher: 'Blizzard · présentation de Shadowlands', url: 'https://worldofwarcraft.blizzard.com/fr-fr/news/23187291/' },
  midnight: { label: 'Le bois des Chants éternels dans Midnight', publisher: 'Blizzard · aperçu de région', url: 'https://worldofwarcraft.blizzard.com/fr-fr/news/24263349' },
};

export const people = [
 { id: 'dathremar', name: 'Dath’Remar', surname: 'Sunstrider', title: 'Le fondateur', era: 'Des Bien-nés à Quel’Thalas', image: 'dathremar.webp', quote: 'L’exil. Puis un royaume.', summary: 'Un chef bien-né qui conduit les siens vers une nouvelle patrie.', paragraphs: ['Dath’Remar appartient aux Bien-nés, les aristocrates de l’ancien empire kaldorei. Après la guerre des Anciens, la pratique de la magie des Arcanes sépare ses partisans de la société des elfes de la nuit.', 'L’exil conduit les siens vers les royaumes de l’Est. La fondation de Quel’Thalas ouvre l’histoire des hauts-elfes et de la maison Sunstrider. Le sanctuaire de Dath’Remar, sur l’île de Haut-Soleil, conserve sa mémoire.'], facts: [['Statut', 'Fondateur de Quel’Thalas'], ['Héritage', 'La maison Sunstrider'], ['Mémoire', 'Sanctuaire de Dath’Remar']], refs: ['founder','dynasty'] },
 { id: 'anasterian', name: 'Anasterian', surname: 'Sunstrider', title: 'Le dernier roi', era: 'Des guerres des Trolls à la Troisième Guerre', image: 'anasterian.webp', quote: 'La grandeur face au désastre.', summary: 'Le souverain dont le règne traverse des siècles de conflits.', paragraphs: ['Arrière-petit-fils de Dath’Remar, Anasterian règne pendant environ 2 800 ans. Son histoire croise les guerres des Trolls, la Deuxième Guerre et les relations difficiles avec l’Alliance de Lordaeron.', 'Lors de la Troisième Guerre, il affronte Arthas pendant l’invasion de Quel’Thalas et meurt au combat. Son fils Kael’thas veut qu’il demeure le dernier roi du royaume.'], facts: [['Lien familial', 'Père de Kael’thas'], ['Fin du règne', 'Invasion du Fléau'], ['Arme dynastique', 'Felo’melorn']], refs: ['king','regent'] },
 { id: 'kaelthas', name: 'Kael’thas', surname: 'Sunstrider', title: 'Le prince déchu', era: 'Warcraft III · The Burning Crusade', image: 'kaelthas.webp', quote: 'Sauver son peuple. À quel prix ?', summary: 'L’héritier d’un royaume brisé, emporté par sa quête de puissance.', paragraphs: ['Après la catastrophe, Kael’thas prend la tête des survivants. Il donne aux elfes de sang leur nom en mémoire des disparus et cherche une réponse à leur dépendance magique.', 'Condamné par Garithos après avoir accepté l’aide des nagas, il rejoint l’Outreterre et Illidan. Il finit par servir Kil’jaeden. Défait au donjon de la Tempête, il revient sur Quel’Danas et meurt à la terrasse des Magistères.'], facts: [['Père', 'Anasterian Sunstrider'], ['Titre', 'Prince, non roi couronné'], ['Fin de parcours', 'Terrasse des Magistères']], refs: ['exile','prince','dynasty'] },
];

export const events = [
 { id: 'exil', era: 'Origines', title: 'Quitter l’ancien monde', text: 'Après la guerre des Anciens, les désaccords sur la magie des Arcanes conduisent les partisans de Dath’Remar à l’exil.', person: 'dathremar', refs: ['founder'], image: 'woods' },
 { id: 'fondation', era: 'Fondation', title: 'Un royaume sous le soleil', text: 'Les hauts-elfes établissent Quel’Thalas. Le Puits de soleil, créé grâce à une fiole d’eau du Puits d’éternité, devient le centre de leur civilisation magique.', person: 'dathremar', refs: ['well','founder'], image: 'well' },
 { id: 'anasterian', era: 'Apogée', title: 'Le temps d’Anasterian', text: 'Les guerres des Trolls puis la Deuxième Guerre jalonnent le règne d’Anasterian. Les alliances du royaume répondent aux menaces qui pèsent sur ses frontières.', person: 'anasterian', refs: ['king'], image: 'court' },
 { id: 'fleau', era: 'Troisième Guerre', title: 'La chute de Quel’Thalas', text: 'Le Fléau envahit le royaume. Anasterian tombe face à Arthas. Le Puits de soleil est souillé lors de la résurrection de Kel’Thuzad.', person: 'anasterian', refs: ['king','exile'], image: 'well' },
 { id: 'sindorei', era: 'Après la chute', title: 'Les enfants du sang', text: 'Kael’thas détruit le Puits corrompu pour protéger son peuple. Les survivants adoptent le nom de Sin’dorei en mémoire des morts.', person: 'kaelthas', refs: ['well','exile'], image: 'court' },
 { id: 'outreterre', era: 'The Frozen Throne', title: 'L’espoir en Outreterre', text: 'L’aide de dame Vashj ouvre à Kael’thas une route vers Illidan. La recherche d’un remède à la soif de magie entraîne le prince loin de Quel’Thalas.', person: 'kaelthas', refs: ['exile'], image: 'court' },
 { id: 'chute', era: 'The Burning Crusade', title: 'La fin de la dynastie', text: 'L’allégeance de Kael’thas à Kil’jaeden le retourne contre son peuple. Sa mort à la terrasse des Magistères met fin à la lignée régnante.', person: 'kaelthas', refs: ['prince','dynasty'], image: 'court' },
 { id: 'renaissance', era: 'Après Quel’Danas', title: 'Une lumière retrouvée', text: 'Après la défaite de Kil’jaeden, Velen utilise le cœur de M’uru pour raviver le Puits de soleil. Lor’themar demeure seigneur régent, sans fonder une nouvelle dynastie.', refs: ['restored','regent'], image: 'well' },
];

export const locations = [
 { id: 'lune-dargent', name: 'Lune-d’Argent', type: 'La capitale', image: 'hero', x: 67, y: 52, text: 'La capitale de Quel’Thalas porte la mémoire du royaume et de ses transformations. Son apparence dépend de l’époque du jeu : cet atlas évoque le cadre historique, sans reproduire la carte de Midnight.', refs: ['midnight'] },
 { id: 'bois-des-chants-eternels', name: 'Bois des Chants éternels', type: 'Le territoire', image: 'woods', x: 49, y: 72, text: 'Les paysages dorés autour de Lune-d’Argent forment l’un des décors emblématiques des elfes de sang. Midnight revisite cette région ; les lieux et les événements doivent donc être lus dans leur contexte.', refs: ['midnight'] },
 { id: 'ile-de-haut-soleil', name: 'Île de Haut-Soleil', type: 'La mémoire du fondateur', image: 'woods', x: 26, y: 39, text: 'Le sanctuaire de Dath’Remar y rappelle la fondation du royaume. Ce lieu de mémoire relie les premiers pas des aventuriers elfes de sang à l’histoire de la dynastie.', refs: ['founder'] },
 { id: 'quel-danas', name: 'Quel’Danas', type: 'Le Puits de soleil', image: 'well', x: 55, y: 18, text: 'L’île abrite le Puits de soleil et la terrasse des Magistères. Elle est au centre du dernier chapitre de Kael’thas dans The Burning Crusade et de la restauration du Puits.', refs: ['prince','restored'] },
];
